version: '3.9'

services:

  backend:
    depends_on:
        - db
    build: .
    command: sh -c "uvicorn hotel_app_backend.asgi:application --host 0.0.0.0 --port 8000 --reload"
    ports:
      - '8000:8000'
    volumes:
      - .:/hotelapp-docker
    stdin_open: true
    tty: true
    
    environment:
      - PORT=8000

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: hotel_app_v1
      POSTGRES_USER: hotel_user
      POSTGRES_PASSWORD: 123456
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  data:
  postgres_data:
