name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: super-linter/super-linter@v4
        with:
          linters:
            - flake8
            - pylint
          extensions:
            - py