# Generated by Django 5.0.1 on 2024-03-01 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_customer_first_name_alter_customer_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='deleted_at',
        ),
    ]
