# Generated by Django 4.2.8 on 2024-01-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelowner',
            name='profile_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
