# Generated by Django 4.2.8 on 2024-01-12 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_hotelowner_profile_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HotelOwner',
            new_name='Owner',
        ),
    ]
