# Generated by Django 4.2.8 on 2024-01-15 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_bathroomtype_bedtype_commonamenities_experienceslot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertytype',
            old_name='time_duration',
            new_name='bid_time_duration',
        ),
    ]
