# Generated by Django 5.0.1 on 2024-01-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_property_updateinventoryperiod_roominventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FCMToken',
        ),
        migrations.AddField(
            model_name='owner',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
