# Generated by Django 5.0.1 on 2024-01-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_delete_fcmtoken_owner_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='gst',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='owner',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='government_id',
            field=models.TextField(blank=True, null=True, verbose_name='gov_id'),
        ),
    ]
