# Generated by Django 5.0.1 on 2024-01-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_owner_gst_owner_is_email_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='property',
            name='hotel_name',
        ),
        migrations.AddField(
            model_name='owner',
            name='hotel_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Hotel Name'),
        ),
        migrations.AddField(
            model_name='property',
            name='parent_hotel_group',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Parent Hotel Group'),
        ),
        migrations.AlterField(
            model_name='property',
            name='manager_name',
            field=models.CharField(max_length=30, verbose_name='Manager Name'),
        ),
    ]
