# Generated by Django 5.0.1 on 2024-01-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
    ]
