# Generated by Django 5.0.1 on 2024-01-29 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_property_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roominventory',
            name='is_updated_period',
        ),
        migrations.RemoveField(
            model_name='roominventory',
            name='updated_period',
        ),
        migrations.AddField(
            model_name='updateinventoryperiod',
            name='room_inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_room', to='hotel.roominventory'),
        ),
        migrations.AlterField(
            model_name='roominventory',
            name='bathroom_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_bathroom_type', to='hotel.bathroomtype'),
        ),
        migrations.AlterField(
            model_name='roominventory',
            name='bed_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_bed_type', to='hotel.bedtype'),
        ),
    ]
