# Generated by Django 5.0.1 on 2024-02-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_remove_roominventory_is_updated_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='welcome_mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
