# Generated by Django 5.0.1 on 2024-02-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0016_owner_welcome_mail_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roominventory',
            name='bed_type',
        ),
        migrations.AddField(
            model_name='roominventory',
            name='bed_type',
            field=models.ManyToManyField(related_name='property_bed_type', to='hotel.bedtype'),
        ),
    ]
