# Generated by Django 5.0.1 on 2024-02-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_remove_roominventory_bed_type_roominventory_bed_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='check_in_datetime',
        ),
        migrations.RemoveField(
            model_name='property',
            name='check_out_datetime',
        ),
        migrations.AddField(
            model_name='property',
            name='check_in_time',
            field=models.CharField(blank=True, null=True, verbose_name='Check-in time'),
        ),
        migrations.AddField(
            model_name='property',
            name='check_out_time',
            field=models.CharField(blank=True, null=True, verbose_name='Check-out time'),
        ),
    ]
