# Generated by Django 5.0.1 on 2024-02-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0019_category_remove_propertytype_bid_time_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='commonamenities',
            options={'verbose_name_plural': 'Common amenities'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='roominventory',
            options={'verbose_name_plural': 'Room inventories'},
        ),
        migrations.AddField(
            model_name='roominventory',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
