# Generated by Django 5.0.1 on 2024-02-07 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0020_alter_category_options_alter_commonamenities_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_category', to='hotel.category'),
        ),
    ]
