# Generated by Django 5.0.1 on 2024-02-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0021_owner_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='hotel_phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
