# Generated by Django 5.0.1 on 2024-02-08 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0022_biddingsession_propertydeal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertydeal',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='propertydeal',
            old_name='property_id',
            new_name='property',
        ),
        migrations.RenameField(
            model_name='propertydeal',
            old_name='session_id',
            new_name='session',
        ),
    ]
