# Generated by Django 5.0.1 on 2024-02-09 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0022_alter_property_hotel_phone_number'),
        ('hotel', '0023_rename_customer_id_propertydeal_customer_and_more'),
    ]

    operations = [
    ]
