# Generated by Django 5.0.1 on 2024-02-12 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0024_merge_20240209_0724'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='RoomImage',
        ),
        migrations.RenameField(
            model_name='roomimage',
            old_name='room_image',
            new_name='room',
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.property')),
            ],
        ),
    ]
