# Generated by Django 5.0.1 on 2024-02-12 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0025_rename_image_roomimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image',
        ),
    ]
