# Generated by Django 5.0.1 on 2024-02-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0026_remove_property_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="hotel_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Hotel Name"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="hotel_nick_name",
            field=models.CharField(max_length=255, verbose_name="Hotel Nick Name"),
        ),
        migrations.AlterField(
            model_name="property",
            name="manager_name",
            field=models.CharField(max_length=255, verbose_name="Manager Name"),
        ),
        migrations.AlterField(
            model_name="property",
            name="parent_hotel_group",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Parent Hotel Group"
            ),
        ),
        migrations.AlterField(
            model_name="roominventory",
            name="room_name",
            field=models.CharField(max_length=255, verbose_name="Room Name"),
        ),
        migrations.AlterField(
            model_name="roominventory",
            name="room_view",
            field=models.CharField(max_length=255, verbose_name="Room View"),
        ),
        migrations.AlterField(
            model_name="updateinventoryperiod",
            name="update_duration",
            field=models.CharField(max_length=255, verbose_name="Update Duration"),
        ),
    ]
