# Generated by Django 5.0.1 on 2024-02-16 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_customer_first_name_alter_customer_last_name'),
        ('hotel', '0027_alter_owner_hotel_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_rooms', models.IntegerField(verbose_name='number_of_book_rooms')),
                ('order_id', models.CharField(max_length=20)),
                ('check_in_date', models.DateTimeField()),
                ('check_out_date', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=3)),
                ('book_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_book', to='customer.customer')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_book', to='hotel.property')),
                ('property_deal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_deal', to='hotel.propertydeal')),
                ('rooms', models.ManyToManyField(related_name='rooms_book', to='hotel.roominventory')),
            ],
        ),
    ]
