# Generated by Django 5.0.1 on 2024-02-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0028_bookinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominventory',
            name='deal_price',
            field=models.IntegerField(default=None, null=True, verbose_name='Deal Price'),
        ),
    ]
