# Generated by Django 5.0.1 on 2024-02-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0029_roominventory_deal_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateinventoryperiod',
            name='deal_price',
            field=models.IntegerField(default=None, null=True, verbose_name='Deal Price'),
        ),
    ]
