# Generated by Django 5.0.1 on 2024-02-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0030_updateinventoryperiod_deal_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominventory',
            name='num_of_rooms',
            field=models.IntegerField(default=0, verbose_name='Num Of Rooms'),
        ),
    ]
