# Generated by Django 5.0.1 on 2024-02-23 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0031_roominventory_num_of_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinghistory',
            name='rooms',
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='rooms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_book', to='hotel.roominventory'),
        ),
    ]
