# Generated by Django 5.0.1 on 2024-02-23 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0032_remove_bookinghistory_rooms_bookinghistory_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghistory',
            name='cancel_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='cancel_reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='is_cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GuestDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_adults', models.IntegerField()),
                ('no_of_children', models.IntegerField()),
                ('age_of_children', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_history', to='hotel.bookinghistory')),
            ],
        ),
    ]
