# Generated by Django 5.0.1 on 2024-02-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0033_bookinghistory_cancel_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghistory',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
