# Generated by Django 5.0.1 on 2024-03-01 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0034_bookinghistory_is_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='cancellation_days',
        ),
        migrations.RemoveField(
            model_name='property',
            name='cancellation_policy',
        ),
        migrations.AddField(
            model_name='property',
            name='commission_percent',
            field=models.FloatField(default=10.0, verbose_name='Commission'),
        ),
        migrations.CreateModel(
            name='PropertyCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancellation_days', models.IntegerField(verbose_name='Cancellation Days')),
                ('cancellation_percents', models.IntegerField(verbose_name='Cancellation Percents')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.property')),
            ],
        ),
    ]
