# Generated by Django 5.0.1 on 2024-03-01 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0035_hotelownerbanking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HotelOwnerBanking',
            new_name='OwnerBankingDetail',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=20)),
                ('settlements_account_number', models.CharField(max_length=20)),
                ('settlements_ifsc_code', models.CharField(max_length=20)),
                ('settlements_beneficiary_name', models.CharField(max_length=20)),
                ('tnc_accepted', models.BooleanField(default=True)),
                ('owner_banking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banking_id', to='hotel.ownerbankingdetail')),
            ],
        ),
    ]
