# Generated by Django 5.0.1 on 2024-03-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0035_remove_property_cancellation_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bathroomtype',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='bedtype',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='biddingsession',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='bookinghistory',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='commonamenities',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='experienceslot',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='guestdetail',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='property',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='propertydeal',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='propertytype',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='roomfeature',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='roomimage',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='roominventory',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='updateinventoryperiod',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='property',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is Verified'),
        ),
        migrations.AlterField(
            model_name='roominventory',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is Verified'),
        ),
    ]
