# Generated by Django 5.0.1 on 2024-03-05 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0038_product_created_at_product_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='deleted_at',
        ),
    ]
