# Generated by Django 5.0.1 on 2024-03-07 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0040_subscriptionplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration',
            field=models.IntegerField(choices=[(3, '3 months'), (6, '6 months'), (12, '12 months')], verbose_name='Plan Duration'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.IntegerField(verbose_name='Price'),
        ),
        migrations.CreateModel(
            name='SubscriptionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_subscription', to='hotel.owner')),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plan', to='hotel.subscriptionplan')),
            ],
        ),
    ]
