# Generated by Django 5.0.1 on 2024-03-11 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_remove_customer_deleted_at'),
        ('hotel', '0041_alter_subscriptionplan_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestdetail',
            old_name='booking_id',
            new_name='booking',
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.IntegerField()),
                ('review', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_ratings', to='customer.customer')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_ratings', to='hotel.property')),
            ],
        ),
    ]
