# Generated by Django 5.0.1 on 2024-03-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0043_bookinghistory_payment_id_bookinghistory_transfer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='hotel_class',
            field=models.IntegerField(default=0),
        ),
    ]
