# Generated by Django 5.0.1 on 2024-03-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0044_property_hotel_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updateinventoryperiod',
            name='common_amenities',
        ),
        migrations.RemoveField(
            model_name='updateinventoryperiod',
            name='update_duration',
        ),
        migrations.AddField(
            model_name='updateinventoryperiod',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='updateinventoryperiod',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
