# Generated by Django 5.0.1 on 2024-03-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0046_updateinventoryperiod_num_of_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateinventoryperiod',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='updateinventoryperiod',
            name='default_price',
            field=models.IntegerField(null=True, verbose_name='Default Price'),
        ),
        migrations.AlterField(
            model_name='updateinventoryperiod',
            name='max_price',
            field=models.IntegerField(null=True, verbose_name='Max Price'),
        ),
        migrations.AlterField(
            model_name='updateinventoryperiod',
            name='min_price',
            field=models.IntegerField(null=True, verbose_name='Min Price'),
        ),
    ]
