# Generated by Django 5.0.1 on 2024-03-20 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0049_cancellationreason_subcancellationreason'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='updateinventoryperiod',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='updateinventoryperiod',
            name='start_date',
        ),
        migrations.AddField(
            model_name='updateinventoryperiod',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='updateinventoryperiod',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='updateinventoryperiod',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_type', to='hotel.updatetype'),
        ),
    ]
