# Generated by Django 5.0.1 on 2024-03-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0050_updatetype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerbankingdetail',
            name='status',
        ),
        migrations.AddField(
            model_name='ownerbankingdetail',
            name='status_bank',
            field=models.BooleanField(default=True),
        ),
    ]
