# Generated by Django 5.0.1 on 2024-03-21 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0051_remove_ownerbankingdetail_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownerbankingdetail',
            old_name='status_bank',
            new_name='status',
        ),
    ]
