# Generated by Django 5.0.1 on 2024-03-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0052_rename_status_bank_ownerbankingdetail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghistory',
            name='cancel_by_owner',
            field=models.BooleanField(default=False),
        ),
    ]
