# Generated by Django 5.0.1 on 2024-04-09 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_remove_customer_deleted_at'),
        ('hotel', '0053_bookinghistory_cancel_by_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddingsession',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_bid_id', to='customer.customer'),
        ),
    ]
