# Generated by Django 5.0.1 on 2024-04-11 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0054_biddingsession_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertydeal',
            name='property',
        ),
        migrations.AddField(
            model_name='propertydeal',
            name='roominventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_id', to='hotel.roominventory'),
        ),
    ]
