# Generated by Django 5.0.1 on 2024-04-11 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0055_remove_propertydeal_property_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiddingAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('property_deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_deal_id', to='hotel.propertydeal')),
            ],
        ),
    ]
