# Generated by Django 5.0.1 on 2024-04-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0057_bookinghistory_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinghistory',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
