# Generated by Django 5.0.1 on 2024-04-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0058_alter_bookinghistory_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='updaterequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='updaterequest',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
