# Generated by Django 5.0.1 on 2024-04-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0059_updaterequest_deleted_at_updaterequest_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='bidding_mode',
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_online',
        ),
        migrations.AddField(
            model_name='property',
            name='bidding_mode',
            field=models.BooleanField(default=False),
        ),
    ]
