# Generated by Django 5.0.1 on 2024-04-19 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0056_biddingamount'),
        ('hotel', '0059_updaterequest_deleted_at_updaterequest_is_deleted'),
    ]

    operations = [
    ]
