# Generated by Django 5.0.1 on 2024-04-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0060_remove_owner_bidding_mode_remove_property_is_online_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='bidding_mode',
        ),
        migrations.AddField(
            model_name='owner',
            name='bidding_mode',
            field=models.BooleanField(default=False),
        ),
    ]
