# Generated by Django 5.0.1 on 2024-05-01 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0060_merge_20240419_1659'),
        ('hotel', '0061_remove_property_bidding_mode_owner_bidding_mode'),
    ]

    operations = [
    ]
