# Generated by Django 5.0.1 on 2024-05-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0063_propertydeal_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertydeal',
            old_name='roominventory',
            new_name='room_inventory',
        ),
        migrations.AddField(
            model_name='biddingsession',
            name='check_in_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biddingsession',
            name='check_out_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biddingsession',
            name='no_of_adults',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biddingsession',
            name='no_of_children',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biddingsession',
            name='num_of_rooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='number_of_rooms'),
        ),
    ]
