name: Deploy to EC2

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Connect to EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.EC2_PORT }}
        script: |
          set -e  # Exit on error

          echo "Changing directory to /home/ubuntu/hotel_app_backend"
          cd /home/ubuntu/hotel_app_backend

          echo "Pulling code from the 'development' branch"
          git pull origin development

          echo "Activating virtual environment"
          source venv/bin/activate

          echo "Installing Python dependencies"
          pip3 install -r requirements.txt

          echo "Restarting Gunicorn service"
          sudo systemctl restart gunicorn

          echo "Deployment successful"
