name: Deploy to EC2

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Connect to EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.EC2_PORT }}
        script: |
          cd /home/ubantu/hotel_app_backend
          git pull origin development
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart gunicorn
  
  rollback:
    runs-on: ubuntu-latest
    needs: deploy
    if: failure()
    steps:
    - name: Checkout code for rollback
      uses: actions/checkout@v2
      with:
        ref: ${{ needs.deploy.outputs['commit_sha'] }}

    - name: Connect to EC2 instance and rollback
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.EC2_PORT }}
        script: |
          cd /home/ec2-user/backend
          git reset --hard HEAD^
          sudo systemctl restart gunicorn

