name: Deploy to EC2

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git config --global credential.helper store
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        GITHUB_USERNAME: ${{ github.actor }}

    - name: Connect to EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.EC2_PORT }}
        script: |
          cd /home/ubuntu/hotel_app_backend
          git pull origin development
          source venv/bin/activate
          pip3 install -r requirements.txt
          sudo systemctl restart gunicorn
